### ISSUE TITLE
Cerebro crashes after update to 0.3.2.

### ISSUE THREAD

**Issue by scmanjarrez** [cerebroapp/cerebro#434]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Cerebro.app version**: 0.3.2
- **Relevant information from devtools** 

I have cerebro in start up applications, so these box came up after log in.

![screenshot from 2017-12-08 03-44-48](https://user-images.githubusercontent.com/9284124/33748841-0d9d261c-dbcb-11e7-92e9-842460c50963.png)

![screenshot from 2017-12-08 03-45-37](https://user-images.githubusercontent.com/9284124/33749026-fe2acdf0-dbcb-11e7-9ca5-a82f26f10a50.png)

Starting from command line throws this error: 

> /opt/Cerebro/resources/electron.asar/common/reset-search-paths.js:0
> 
> 
> 
> Error: Cannot find module '../dialog'
>     at Module._resolveFilename (module.js:470:15)
>     at Function.Module._resolveFilename (/opt/Cerebro/resources/electron.asar/common/reset-search-paths.js:35:12)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.get [as dialog] (/opt/Cerebro/resources/electron.asar/browser/api/exports/electron.js:11:16)
>     at process.<anonymous> (/opt/Cerebro/resources/electron.asar/browser/init.js:54:31)
>     at emitOne (events.js:96:13)
>     at process.emit (events.js:188:7)
>     at process._fatalException (bootstrap_node.js:300:26)

## Issue

Cerebro crashes on start. I have reinstalled 2 times without success.

**Comment by lawgsy** [comment]
Hello, the current release version is broken for some. See https://github.com/KELiON/cerebro/issues/423. It was fixed [here](https://github.com/KELiON/cerebro/commit/b379a5b90ba63df99155210ef043d69ae785e6a6), but somehow managed to get into the release.

In other words, if you're feeling adventurous you should be able to compile from source. If not, please wait until the next (re)release. I'm guessing that shouldn't take too long.

**Comment by FreaKzero** [comment]
The "easy fix" for me was to disable tracking in the config.json file of cerebro.

**Comment by yusunglee2074** [comment]
Freakzero //

Can I know where that file(trackEvent.js) is? on Ubuntu 16.04

I'm noobie.

**Comment by evrohachik** [comment]
same for me
donwgraded for previous version

**Comment by FreaKzero** [comment]
@yusunglee2074 The config on linux should be there (as described in the README of Cerebro) `$XDG_CONFIG_HOME/Cerebro/config.json or ~/.config/Cerebro/config.json`

And there set trackingEnabled to false and remove every in the positions property (like this:`positions: {}`)

or downgrade until this bug is fixed

**Comment by yusunglee2074** [comment]
@FreaKzero thank you very much.
Now I'm in Cerebro.
It awesome.

**Comment by lawgsy** [comment]
Just for completion, on Windows the path would be `%appdata%\Cerebro\config.json`

**Comment by DanielSokil** [comment]
Same Issue.

**Comment by Haarolean** [comment]
@KELiON Currently your master branch is broken for at least one month. This extends to stable builds from your website, I get the same exceptions out of the box. You gonna fix this?
https://github.com/KELiON/cerebro/issues/423
https://github.com/KELiON/cerebro/issues/434

**Comment by The-Log** [comment]
Similar issue, but now it doesn't even display that error and crashes.

**Comment by pocheche** [comment]
Same issue on Gnome Manjaro Linux going back to previous.

**Comment by raice** [comment]
Same issue on Ubuntu 17.10. Workaround with disable tracking works

**Comment by luisdavim** [comment]
Same issue on MacOS

**Comment by luisdavim** [comment]
As @FreaKzero mentioned setting `trackingEnabled` to `false` and emptying the `positions` object clears the issue.

**Comment by najit97** [comment]
I can confirm that setting `trackingEnabled: false` in `~/.config/Cerebro/config.json` fixes the issue in Ubuntu 18.04.

First impression of Cerebro is amazing ! Thank you @KELiON

**Comment by mybluevan** [comment]
Confirming the `trackingEnabled: false` and `positions: {}` fix for OSX 10.13.4. Any word on a timeline? Looks like the code hasn't been touched since February. If it's a matter of manpower I'd be willing to help out, it's a nice app.

**Comment by rogusdev** [comment]
Still experiencing this (windows 10).  Cerebro is a great concept and I really want this to succeed, but it won't if it takes more than 6 months to fix a bug that prevents every single new user from using the latest version!

**Comment by http403** [comment]
Same here. I tried to compile (`master` and `tags/v0.3.0`), no luck. I even downgraded to 0.3.0 official build and it still throwing errors to me. Running in Ubuntu 18.04.

**Comment by http403** [comment]
Successfully build an AppImage version from `master` branch and confirmed it run flawlessly. [Cerebro v0.3.3 AppImage Download](https://transfer.sh/oJRDA/cerebro-0.3.3)

**Comment by najit97** [comment]
@http403 AppImage is not available in the link you have provided.

**Comment by crustaceo1992** [comment]
I'm using google translator.

Here I had this error in my Linux Mint 19.1, solve this problem by removing version 0.3.2, after removing version 0.3.2 I removed the brain folder that is in the home / .config.
Then I installed version 0.3.0

----

Original text

Aqui tive esse erro no meu Linux Mint 19.1, resolve esse problema removendo a versão 0.3.2, depois de remover a versão 0.3.2 eu removi a pasta cerebro que fica na home/.config.
Depois instalei a versão 0.3.

**Comment by alxrodriguez** [comment]
I can confirm that setting trackingEnabled: false in ~/.config/Cerebro/config.json fixes the issue in SO Deepin 15.9

I love Cerebro is amazing ! Thank you @KELiON

**Comment by phanirithvij** [comment]
On Windows, the path for config.json was `C:\Users\USERNAME\AppData\Roaming\Cerebro\config.json`

**Comment by weijing24** [comment]
> On macOS 10.14.1
> 
> Editing in `~/Library/Application\ Support/Cerebro/config.json` value `trackingEnabled: false` fixed the issues.

it works

**Comment by moeabdol** [comment]
Editing ~/.config/Cerebero/config.json fixed in on Ubuntu 18.04.
Note that it sometimes doesn't show the menu bar icon, so try to press ctrl+space to check it out.

**Comment by PankajPrakashh** [comment]
Works like charm in Ubuntu 19.10 just set `trackingEnabled: false` in `~/.config/Cerebro/config.json`.

Kudos.

**Comment by ajithkumar-natarajan** [comment]
> Works like charm in Ubuntu 19.10 just set `trackingEnabled: false` in `~/.config/Cerebro/config.json`.
> 
> Kudos.

I am using it on Ubuntu 19.10 too. What was the need for you to set that parameter?
Also, none of the plugins I install are being recognized. Any solutions?

**Comment by PankajPrakashh** [comment]
> > Works like charm in Ubuntu 19.10 just set `trackingEnabled: false` in `~/.config/Cerebro/config.json`.
> > Kudos.
> 
> I am using it on Ubuntu 19.10 too. What was the need for you to set that parameter?
> Also, none of the plugins I install are being recognized. Any solutions?

On every login it was throwing errors.

**Comment by dubisdev** [comment]
The issue with `screenview` has been solved as we have removed the tracking analytics.

You can test with the new release `v0.7.1` and if this problem persists we will open another issue as this is too outdated.
